### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by joelhandwell** [sourcegraph/java-langserver-docs#1]
I was using source graph chrome plugin on github and was not able to jump to the definition. Not sure if here is right place to make issue but does source graph supports Kotlin language? Is there issue tracker for new language support?

**Comment by emidoots** [comment]
Hi, this is definitely something we want to support, we've got this issue open on our general issue tracker for adding Kotlin support: https://github.com/sourcegraph/issues/issues/2

I'll close this issue in favor of that one for now.
